config/routes.rb
Rails.application.routes.draw do
  resources :board_games

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_and_belongs_to_many :board_games
end

app/models/board_game.rb
class BoardGame < ActiveRecord::Base
  def self.parse(games_xml)
    Hash.from_xml(games_xml)["items"]["item"].each do |game_hash|
      categories = game_hash["link"].select {|link| link["type"] == "boardgamecategory"}.map do |category_hash|
        Category.find_or_create_by(bgg_id: category_hash["id"], name: category_hash["value"])
      end

      mechanics = game_hash["link"].select {|link| link["type"] == "boardgamemechanic"}.map do |mechanic_hash|
        Mechanic.find_or_create_by(bgg_id: mechanic_hash["id"], name: mechanic_hash["value"])
      end

      families = game_hash["link"].select {|link| link["type"] == "boardgamefamily"}.map do |family_hash|
        Family.find_or_create_by(bgg_id: family_hash["id"], name: family_hash["value"])
      end

      publishers = game_hash["link"].select {|link| link["type"] == "boardgamepublisher"}.map do |publisher_hash|
        Publisher.find_or_create_by(bgg_id: publisher_hash["id"], name: publisher_hash["value"])
      end

      artists = game_hash["link"].select {|link| link["type"] == "boardgameartist"}.map do |artist_hash|
        Artist.find_or_create_by(bgg_id: artist_hash["id"], name: artist_hash["value"])
      end

      BoardGame.create({
        bgg_id: game_hash["id"],
        primary_name: [game_hash["name"]].flatten.select { |name| name["type"] == "primary" }.first["value"],
        image: game_hash["image"],
        names: [game_hash["name"]].flatten.map { |name| name["value"] }.join(","),
        description: game_hash["description"],
        year_published: game_hash["yearpublished"]["value"],
        min_players: game_hash["minplayers"]["value"],
        max_players: game_hash["maxplayers"]["value"],
        playtime: game_hash["playingtime"]["value"],
        bgg_bayes_score: game_hash["statistics"]["ratings"]["bayesaverage"]["value"].to_f,
        bgg_user_score: game_hash["statistics"]["ratings"]["usersrated"]["value"].to_f,
        bgg_average_score: game_hash["statistics"]["ratings"]["average"]["value"].to_f,
        categories: categories,
        mechanics: mechanics,
        families: families,
        publishers: publishers,
        artists: artists
      })
    end
  end

  has_and_belongs_to_many :categories
  has_and_belongs_to_many :mechanics
  has_and_belongs_to_many :families
  has_and_belongs_to_many :publishers
  has_and_belongs_to_many :artists

  default_scope { order(bgg_bayes_score: :desc) }

  def to_s
    self.primary_name
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :board_games
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_and_belongs_to_many :board_games
end

app/models/mechanic.rb
class Mechanic < ActiveRecord::Base
  has_and_belongs_to_many :board_games
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_and_belongs_to_many :board_games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/board_games_controller.rb
class BoardGamesController < ApplicationController

  def index
    @q = BoardGame.search(params[:q])
    @board_games = @q.result(distinct: true).includes(:categories, :mechanics).paginate(:page => params[:page])
  end

  def show
    @board_game = BoardGame.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/board_games/index.html.haml
= search_form_for @q do |f|
  = f.search_field :names_or_categories_name_or_mechanics_name_cont
  = f.submit

%table
  %thead
    %tr
      %th
      = content_tag :th, sort_link(@q, :primary_name, "Name")
      %th Categories
      %th Mechanics
  %tbody
    - @board_games.each do |board_game|
      %tr
        %th= image_tag board_game.image, style: "height: 100px"
        %td= link_to board_game, board_game_path(board_game)
        %td= board_game.categories.map(&:name).join(", ")
        %td= board_game.mechanics.map(&:name).join(", ")


= will_paginate @board_games

app/views/board_games/show.html.haml
= image_tag @board_game.image, style: "height: 500px"

%h2
  =@board_game

%div
  =@board_game.description

%div
  %h3
    Gameplay Information
  %table
    %tr
      %td="Players"
      %td="#{@board_game.min_players} - #{@board_game.max_players}"
    %tr
      %td="Playtime"
      %td="#{@board_game.playtime} minutes"
    %tr
      %td="Categories"
      %td=@board_game.categories.map(&:name).join(", ");
  %h4
    Gameplay Mechanics
  %div
    =@board_game.mechanics.map(&:name).join(", ");

%div
  %h3
    Game Information
  %table
    %tr
      %td="Publisher"
      %td=@board_game.publishers.map(&:name).join(", ")
    %tr
      %td="Published"
      %td=@board_game.year_published
    %tr
      %td="Artists"
      %td=@board_game.artists.map(&:name).join(", ")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoredGamer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>